### ISSUE TITLE
Fxing auth-service with local deployment

### ISSUE THREAD

**Issue by louisfb01** [louisfb01/auth-service#2]
Edited the deploy.js file commenting out the SSL verification for local deployment. Leads to error:

```
Error: Command failed: rm -rf auth-service 2> /dev/null || true && git clone https://github.com/louisfb01/auth-service && cd auth-service && cp ../envs/auth-service.env .env && echo "
" >> .env && cat ../.env >> .env && npm install && npm run caprover:setup && npm run caprover:deploy && cd .. && rm -rf auth-service
    at checkExecSyncError (child_process.js:635:11)
    at execSync (child_process.js:671:15)
    at Object.<anonymous> (/root/hub-deployer/deploy.js:39:5)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 7343,
  stdout: null,
  stderr: null
}
```

**Comment by louisfb01** [comment]
Fixed putting forceSsl to false in [update.json](https://github.com/louisfb01/auth-service/blob/main/caprover/update.json).
